In [11]:
import os
os.environ['OMOL_MODEL_PATH'] = '/Users/mgt16/fairchem_models/esen_sm_conserving_all.pt'
from architector import build_complex, convert_io_molecule, CalcExecutor, view_structures

In [105]:
from architector.io_ptable import ligands_dict
from ase import units
import numpy as np

In [13]:
mol = convert_io_molecule('CCCCCC')
mol.get_dists(atom_type_pairs=[['C','C']])

   atom_pair      bond_type  smiles  ...  distance  sum_cov_radii  atom_symbols
1     (0, 1)  explicit_bond  CCCCCC  ...  1.520050            1.5           C-C
2     (0, 2)  implicit_bond  CCCCCC  ...  2.482209            1.5           C-C
3     (0, 3)  implicit_bond  CCCCCC  ...  3.041699            1.5           C-C
4     (0, 4)  implicit_bond  CCCCCC  ...  3.675875            1.5           C-C
5     (0, 5)  implicit_bond  CCCCCC  ...  4.719581            1.5           C-C
8     (1, 2)  explicit_bond  CCCCCC  ...  1.520038            1.5           C-C
9     (1, 3)  implicit_bond  CCCCCC  ...  2.557695            1.5           C-C
10    (1, 4)  implicit_bond  CCCCCC  ...  3.065700            1.5           C-C
11    (1, 5)  implicit_bond  CCCCCC  ...  3.682086            1.5           C-C
15    (2, 3)  explicit_bond  CCCCCC  ...  1.537216            1.5           C-C
16    (2, 4)  implicit_bond  CCCCCC  ...  2.576263            1.5           C-C
17    (2, 5)  implicit_bond  CCCCCC  ...  3.096336            1.5           C-C
22    (3, 4)  explicit_bond  CCCCCC  ...  1.531767            1.5           C-C
23    (3, 5)  implicit_bond  CCCCCC  ...  2.531975            1.5           C-C
29    (4, 5)  explicit_bond  CCCCCC  ...  1.520435            1.5           C-C

[15 rows x 7 columns]

In [38]:
inputDict = {'core':{'metal':'Fe','coreCN':6}, #Specify metal coordination number (CN)
            'ligands':['bipy']*3, # Specify what is filling the coordination environment
            'parameters':{'full_method':'UFF'}} # No additional parameters needed for default
out1 = build_complex(inputDict) # Now just build using the dictionary!

/Users/mgt16/software/omol_2/Architector/architector/io_core.py:69: RuntimeWarning: invalid value encountered in arccos
  np.arccos(

In [113]:
out1['octahedral_0_nunpairedes_4_charge_2']['metal_center_symmetry']

'octahedral'

In [39]:
mol = convert_io_molecule(out1[list(out1.keys())[0]]['mol2string'])

In [40]:
mol.get_dists()

  atom_pair      bond_type  ... sum_cov_radii  atom_symbols
0    (0, 1)  explicit_bond  ...          1.87          Fe-N
1   (0, 12)  explicit_bond  ...          1.87          Fe-N
2   (0, 21)  explicit_bond  ...          1.87          Fe-N
3   (0, 32)  explicit_bond  ...          1.87          Fe-N
4   (0, 41)  explicit_bond  ...          1.87          Fe-N
5   (0, 52)  explicit_bond  ...          1.87          Fe-N

[6 rows x 7 columns]

In [41]:
view_structures(mol, vis_distances=True)

In [42]:
len(ligands_dict)

146

In [43]:
allowable_denticites=[1,2,3,6]
possible_ligs = []
for key,val in ligands_dict.items():
    ligcharge = convert_io_molecule(val['smiles']).charge
    # print(ligcharge)
    if (len(val['coordList']) in allowable_denticites) and (
        ((ligcharge * int(6/len(val['coordList']))) + 2) > -3
    ) and ('edge' not in val.get('ligType','')) and (
        ('sandwich' not in val.get('ligType',''))
    ):
        possible_ligs.append(val)

In [44]:
len(possible_ligs)

88

In [46]:
possible_ligs[0:3]

[{'smiles': 'O', 'coordList': [0], 'ligType': 'mono', 'ligCharge': 0},
 {'smiles': 'OO', 'coordList': [0], 'ligType': 'mono'},
 {'smiles': 'O=O', 'coordList': [0], 'ligType': 'mono'}]

In [116]:
def eval_lig(lig, task_dict={
    'sco':True,
    'solvents':['water','acetone','octanol','hexane'],
    },
    debug=True):
    """eval_lig
    """
    good = True
    error = ''
    output_dict = dict()
    if task_dict.get('sco', False):
        arch_out = dict()
        nlig = int(6/len(lig['coordList']))
        architector_input = {
            'core':{'metal':'Fe','coreType':'octahedral'},
            'ligands':[lig]*nlig,
            'parameters':{
                'metal_ox':2,
                'metal_spin':4,
                'assemble_method':'UFF',
                'full_method':'UFF'}
        }
        arch_mol = None
        try:
            if debug:
                print('Building Complex')
            arch_out = build_complex(architector_input)
            arch_mol = convert_io_molecule(arch_out[list(arch_out.keys())[0]]['mol2string'])
            output_dict['architector_uff_mol2'] = arch_out[list(arch_out.keys())[0]]['mol2string']
        except Exception as e:
            good = False
            error += e
        if len(arch_out) == 0:
            good = False
            error += 'Architector produced no output'
        else:
            mol = convert_io_molecule(arch_mol)
            mol.uhf = 0
            if debug:
                print('Relaxing LS Complex')
            low_spin = CalcExecutor(mol, method='omol', relax=True, fmax=0.05)
            if low_spin.successful:
                output_dict['low_spin_mol2_omol'] = low_spin.mol.write_mol2('ls',writestring=True)
            else:
                error += 'low spin omol failed'
            if debug:
                print('Relaxing HS Complex')
            mol = convert_io_molecule(arch_mol)
            high_spin = CalcExecutor(mol, method='omol', relax=True, fmax=0.05)
            if high_spin.successful:
                output_dict['high_spin_mol2_omol'] = high_spin.mol.write_mol2('hs',writestring=True)
            else:
                error += 'high spin omol failed'
            if low_spin.successful and high_spin.successful:
                output_dict['sco_kcal'] = (high_spin.energy - low_spin.energy) / (units.kcal/units.mol)
    if good and len(task_dict.get('solvents',[])) > 0:
        for solv in task_dict['solvents']:
            if debug:
                print('Evaluating {} solvent'.format(solv))
            mol = CalcExecutor(arch_mol,
                method='GFN2-xTB', xtb_solvent=solv,
                relax=False, store_results=True)
            if mol.successful:
                output_dict['{}_gsolv_eV'.format(solv)] = mol.results['gsolv_eV']
                output_dict['{}_hl_gap_eV'.format(solv)] = mol.results['hl_gap_eV']
                output_dict['{}_dipole'.format(solv)] = np.linalg.norm(mol.results['dipole'])
            else:
                error += '{} solvent failed XTB'.format(solv)
    if debug:
        print('Done')
    output_dict['error'] = error
    return output_dict

In [115]:
possible_ligs[20]

{'smiles': 'NCCN', 'coordList': [0, 3], 'ligType': 'bi_cis'}

In [110]:
thing = eval_lig(possible_ligs[20])

Building Complex

/Users/mgt16/software/omol_2/Architector/architector/io_lig.py:793: RuntimeWarning: invalid value encountered in sqrt
  L[i, i] = np.sqrt(np.max(l[natoms - 1 - i], 0))
/Users/mgt16/software/omol_2/Architector/architector/io_core.py:69: RuntimeWarning: invalid value encountered in arccos
  np.arccos(

Relaxing LS Complex
Relaxing HS Complex
Evaluating water solvent
Evaluating acetone solvent
Evaluating octanol solvent
Evaluating hexane solvent
Done

In [111]:
thing

{'low_spin_mol2_omol': '@<TRIPOS>MOLECULE\nls Charge: 2 Unpaired_Electrons: 0 XTB_Unpaired_Electrons: 0 XTB_Charge: 2\n    37    39     1     0     0\nSMALL\nNoCharges\n****\nGenerated from Architector\n\n@<TRIPOS>ATOM\n     1 Fe1      -0.0004    0.0475   -0.0449   Fe        1 RES1   0.0000\n     2 N1        0.0128   -0.0882    2.0304   N.4       1 RES1   0.0000\n     3 C1        0.3389   -1.4872    2.4217   C.3       1 RES1   0.0000\n     4 C2       -0.3733   -2.4213    1.4725   C.3       1 RES1   0.0000\n     5 N2       -0.0138   -2.0287    0.0827   N.4       1 RES1   0.0000\n     6 H1        0.6561    0.5359    2.5107   H         1 RES1   0.0000\n     7 H2       -0.8988    0.1431    2.4206   H         1 RES1   0.0000\n     8 H3        0.0662   -1.6971    3.4561   H         1 RES1   0.0000\n     9 H4        1.4182   -1.6255    2.3367   H         1 RES1   0.0000\n    10 H5       -1.4537   -2.3216    1.5902   H         1 RES1   0.0000\n    11 H6       -0.1203   -3.4606    1.6831   H         1 RES1   0.0000\n    12 H7       -0.6383   -2.5116   -0.5582   H         1 RES1   0.0000\n    13 H8        0.9052   -2.4150   -0.1248   H         1 RES1   0.0000\n    14 N3       -0.1554    0.0286   -2.1182   N.4       1 RES1   0.0000\n    15 C3       -1.5472    0.3913   -2.5007   C.3       1 RES1   0.0000\n    16 C4       -2.4934   -0.2768   -1.5295   C.3       1 RES1   0.0000\n    17 N4       -2.0731    0.0809   -0.1477   N.4       1 RES1   0.0000\n    18 H9        0.4869    0.6347   -2.6225   H         1 RES1   0.0000\n    19 H10       0.0389   -0.9010   -2.4844   H         1 RES1   0.0000\n    20 H11      -1.7774    0.1059   -3.5275   H         1 RES1   0.0000\n    21 H12      -1.6441    1.4764   -2.4378   H         1 RES1   0.0000\n    22 H13      -2.4339   -1.3617   -1.6327   H         1 RES1   0.0000\n    23 H14      -3.5263    0.0077   -1.7309   H         1 RES1   0.0000\n    24 H15      -2.5577   -0.5311    0.5038   H         1 RES1   0.0000\n    25 H16      -2.4360    1.0083    0.0628   H         1 RES1   0.0000\n    26 N5        2.0728    0.1537   -0.0731   N.4       1 RES1   0.0000\n    27 C5        2.4907    1.5390    0.2760   C.3       1 RES1   0.0000\n    28 C6        1.5410    2.5046   -0.3951   C.3       1 RES1   0.0000\n    29 N6        0.1514    2.1213   -0.0255   N.4       1 RES1   0.0000\n    30 H17       2.5542   -0.4923    0.5474   H         1 RES1   0.0000\n    31 H18       2.4410   -0.0646   -0.9965   H         1 RES1   0.0000\n    32 H19       3.5226    1.7411   -0.0118   H         1 RES1   0.0000\n    33 H20       2.4331    1.6487    1.3604   H         1 RES1   0.0000\n    34 H21       1.6346    2.4352   -1.4801   H         1 RES1   0.0000\n    35 H22       1.7700    3.5337   -0.1168   H         1 RES1   0.0000\n    36 H23      -0.4941    2.6226   -0.6307   H         1 RES1   0.0000\n    37 H24      -0.0398    2.4902    0.9037   H         1 RES1   0.0000\n@<TRIPOS>BOND\n     1     1     2    1\n     2     1     5    1\n     3     1    14    1\n     4     1    17    1\n     5     1    26    1\n     6     1    29    1\n     7     2     3    1\n     8     2     6    1\n     9     2     7    1\n    10     3     4    1\n    11     3     8    1\n    12     3     9    1\n    13     4     5    1\n    14     4    10    1\n    15     4    11    1\n    16     5    12    1\n    17     5    13    1\n    18    14    15    1\n    19    14    18    1\n    20    14    19    1\n    21    15    16    1\n    22    15    20    1\n    23    15    21    1\n    24    16    17    1\n    25    16    22    1\n    26    16    23    1\n    27    17    24    1\n    28    17    25    1\n    29    26    27    1\n    30    26    30    1\n    31    26    31    1\n    32    27    28    1\n    33    27    32    1\n    34    27    33    1\n    35    28    29    1\n    36    28    34    1\n    37    28    35    1\n    38    29    36    1\n    39    29    37    1\n@<TRIPOS>SUBSTRUCTURE\n     1 RES1       37 GROUP             0 ****  ****    0  \n',
 'high_spin_mol2_omol': '@<TRIPOS>MOLECULE\nhs Charge: 2 Unpaired_Electrons: 4 XTB_Unpaired_Electrons: 4 XTB_Charge: 2\n    37    39     1     0     0\nSMALL\nNoCharges\n****\nGenerated from Architector\n\n@<TRIPOS>ATOM\n     1 Fe1      -0.0001    0.0472   -0.0443   Fe        1 RES1   0.0000\n     2 N1        0.0012   -0.1880    2.2019   N.4       1 RES1   0.0000\n     3 C1        0.3543   -1.5957    2.5204   C.3       1 RES1   0.0000\n     4 C2       -0.3875   -2.5214    1.5787   C.3       1 RES1   0.0000\n     5 N2       -0.0013   -2.2010    0.1800   N.4       1 RES1   0.0000\n     6 H1        0.6309    0.4360    2.6988   H         1 RES1   0.0000\n     7 H2       -0.9180    0.0078    2.5935   H         1 RES1   0.0000\n     8 H3        0.1269   -1.8485    3.5558   H         1 RES1   0.0000\n     9 H4        1.4319   -1.7192    2.3871   H         1 RES1   0.0000\n    10 H5       -1.4654   -2.3705    1.6806   H         1 RES1   0.0000\n    11 H6       -0.1810   -3.5621    1.8294   H         1 RES1   0.0000\n    12 H7       -0.6129   -2.7017   -0.4589   H         1 RES1   0.0000\n    13 H8        0.9237   -2.5896    0.0074   H         1 RES1   0.0000\n    14 N3       -0.2580    0.0132   -2.2878   N.4       1 RES1   0.0000\n    15 C3       -1.6572    0.4060   -2.5999   C.3       1 RES1   0.0000\n    16 C4       -2.5956   -0.2902   -1.6356   C.3       1 RES1   0.0000\n    17 N4       -2.2455    0.0971   -0.2440   N.4       1 RES1   0.0000\n    18 H9        0.3784    0.6091   -2.8099   H         1 RES1   0.0000\n    19 H10      -0.0966   -0.9206   -2.6599   H         1 RES1   0.0000\n    20 H11      -1.9284    0.1688   -3.6292   H         1 RES1   0.0000\n    21 H12      -1.7422    1.4897   -2.4880   H         1 RES1   0.0000\n    22 H13      -2.4849   -1.3735   -1.7270   H         1 RES1   0.0000\n    23 H14      -3.6325   -0.0543   -1.8766   H         1 RES1   0.0000\n    24 H15      -2.7428   -0.5077    0.4035   H         1 RES1   0.0000\n    25 H16      -2.6191    1.0270   -0.0647   H         1 RES1   0.0000\n    26 N5        2.2445    0.2519   -0.0867   N.4       1 RES1   0.0000\n    27 C5        2.5927    1.6471    0.2902   C.3       1 RES1   0.0000\n    28 C6        1.6507    2.6047   -0.4103   C.3       1 RES1   0.0000\n    29 N6        0.2532    2.2930   -0.0111   N.4       1 RES1   0.0000\n    30 H17       2.7389   -0.3901    0.5265   H         1 RES1   0.0000\n    31 H18       2.6225    0.0637   -1.0130   H         1 RES1   0.0000\n    32 H19       3.6286    1.8885    0.0501   H         1 RES1   0.0000\n    33 H20       2.4847    1.7461    1.3731   H         1 RES1   0.0000\n    34 H21       1.7328    2.4848   -1.4934   H         1 RES1   0.0000\n    35 H22       1.9213    3.6362   -0.1818   H         1 RES1   0.0000\n    36 H23      -0.3854    2.8127   -0.6067   H         1 RES1   0.0000\n    37 H24       0.0951    2.6693    0.9217   H         1 RES1   0.0000\n@<TRIPOS>BOND\n     1     1     2    1\n     2     1     5    1\n     3     1    14    1\n     4     1    17    1\n     5     1    26    1\n     6     1    29    1\n     7     2     3    1\n     8     2     6    1\n     9     2     7    1\n    10     3     4    1\n    11     3     8    1\n    12     3     9    1\n    13     4     5    1\n    14     4    10    1\n    15     4    11    1\n    16     5    12    1\n    17     5    13    1\n    18    14    15    1\n    19    14    18    1\n    20    14    19    1\n    21    15    16    1\n    22    15    20    1\n    23    15    21    1\n    24    16    17    1\n    25    16    22    1\n    26    16    23    1\n    27    17    24    1\n    28    17    25    1\n    29    26    27    1\n    30    26    30    1\n    31    26    31    1\n    32    27    28    1\n    33    27    32    1\n    34    27    33    1\n    35    28    29    1\n    36    28    34    1\n    37    28    35    1\n    38    29    36    1\n    39    29    37    1\n@<TRIPOS>SUBSTRUCTURE\n     1 RES1       37 GROUP             0 ****  ****    0  \n',
 'sco_kcal': -3.190377563621426,
 'water_gsolv_eV': -7.922752265743467,
 'water_hl_gap_eV': 4.516591907093,
 'water_dipole': np.float64(0.24009373169660217),
 'acetone_gsolv_eV': -7.8197554133095375,
 'acetone_hl_gap_eV': 4.711246301241,
 'acetone_dipole': np.float64(0.23562257956316496),
 'octanol_gsolv_eV': -7.4965914473318485,
 'octanol_hl_gap_eV': 4.791121058046,
 'octanol_dipole': np.float64(0.22284748147555986),
 'hexane_gsolv_eV': -4.462339388753412,
 'hexane_hl_gap_eV': 4.65167060408,
 'hexane_dipole': np.float64(0.22167318286161725),
 'error': ''}

In [75]:
view_structures(thing['low_spin_mol2_omol'],vis_distances=True)

In [103]:
view_structures(thing['high_spin_mol2_omol'],vis_distances=True)

In [104]:
mol.results.keys()

dict_keys(['sas', 'born_radii', 'gsolv_eV', 'hl_gap_eV', 'energy', 'forces', 'charges', 'coveCNs', 'dipole'])

In [102]:
mol.mol.get_rad_gyration()

np.float64(2.269138123355023)